#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        TPM_DS.py
## 
## Project :     AAVS Tango TPM Driver
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      andrea.demarco$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""A Tango device server for the TPM board."""

__all__ = ["TPM_DS", "TPM_DSClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
from FPGA_DS import FPGA_DS, FPGA_DSClass
# Add additional import
#----- PROTECTED REGION ID(TPM_DS.additionnal_import) ENABLED START -----#
from PyTango import DevState
from pyfabil import TPM, BoardState
#----- PROTECTED REGION END -----#	//	TPM_DS.additionnal_import

## Device States Description
## No states for this device

class TPM_DS (FPGA_DS):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(TPM_DS.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TPM_DS.global_variables

    def __init__(self,cl, name):
        super(TPM_DS,self).__init__(cl,name)
        self.debug_stream("In __init__()")
        TPM_DS.init_device(self)
        #----- PROTECTED REGION ID(TPM_DS.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(TPM_DS.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        #----- PROTECTED REGION ID(TPM_DS.init_device) ENABLED START -----#
        self.fpga_instance = TPM()
        #----- PROTECTED REGION END -----#	//	TPM_DS.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(TPM_DS.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.always_executed_hook

    #-----------------------------------------------------------------------------
    #    TPM_DS read/write attribute methods
    #-----------------------------------------------------------------------------
    
    
    
        #----- PROTECTED REGION ID(TPM_DS.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(TPM_DS.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    TPM_DS command methods
    #-----------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(TPM_DS.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TPM_DS.programmer_methods

class TPM_DSClass(FPGA_DSClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(TPM_DS.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TPM_DS.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`TPM_DS.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(TPM_DS.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.dyn_attr

    #    Class Properties
    class_property_list = {
        }
    class_property_list.update(FPGA_DSClass.class_property_list)


    #    Device Properties
    device_property_list = {
        }
    device_property_list.update(FPGA_DSClass.device_property_list)


    #    Command definitions
    cmd_list = {
        }
    cmd_list.update(FPGA_DSClass.cmd_list)


    #    Attribute definitions
    attr_list = {
        }
    attr_list.update(FPGA_DSClass.attr_list)


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(TPM_DSClass,TPM_DS,'TPM_DS')
        #----- PROTECTED REGION ID(TPM_DS.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TPM_DS.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
